name: Save Replicate Prediction

on:
  repository_dispatch:

jobs:
  save-replicate-prediction:
    runs-on: ubuntu-latest
    env:
      PAYLOAD: ${{ toJson(github.event.client_payload) }}
      ID: ${{ github.event.client_payload.id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save payload to file
        run: |
          echo "Payload: $PAYLOAD"
          echo "ID: $ID"
          echo "$PAYLOAD" > "predictions/${ID}.json"

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -am "Save prediction ${ID}"
          git push
